<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Procedure [] >
  <Procedure
      designNotes="Undefined"
      isTPL="false"
      language="EcmaScript"
      name="testUnexpectedExceptionMsg"
      nested="false"
      version="4.1.0">
    <ReferenceParameters />
    <ProcedureLocals>
    </ProcedureLocals>
    <Verbatim
        fieldName="text">
<![CDATA[mockUtpAssertor =  Mock.createMock(UtpAssertor);
Mock.expect(mockUtpAssertor.assertTrue(true));
Mock.expect(mockUtpAssertor.setTestName("TestTools.TestUnit.Tests.Objects.WasRunTestException__testWhichThrowsAnExceptionOfTypeExcpectedButDifMsg"));
Mock.expect(mockUtpAssertor.assert(false, "Expected GT.Runtime.Exceptions.InviteCancelledException('An invite cancelled exception')"+
                                          " but was a GT.Runtime.Exceptions.InviteCancelledException('A different message')"));
Mock.replay(mockUtpAssertor);

wasRun = new WasRunTestException("testWhichThrowsAnExceptionOfTypeExcpectedButDifMsg", mockUtpAssertor);

wasRun.run(this);

Mock.verify(mockUtpAssertor,this);
]]>
    </Verbatim>
  </Procedure>
